apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-dep-label
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-app
  template:
    metadata:
      labels:
        name: postgres-pod
        app: demo-app
    spec:
      containers:
      - name: postgres
        image: postgres:9.4
        env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
        ports:
        - containerPort: 5432



