apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  labels:
    app: result-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-pod
  template:
    metadata:
      labels:
        app: result-pod
    spec:
      containers:
      - name: result-pod
        image: kodekloud/examplevotingapp_result:v1
        ports:
        - containerPort: 80

