apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-deployment
  labels:
    app: vote-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-app
  template:
    metadata:
      labels:
        app: vote-app
    spec:
      containers:
      - name: voteing-pod
        image: kodekloud/examplevotingapp_vote:v1
        ports:
        - containerPort: 80

